name: Lint
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
